models/didgit.py
from extensions import db


class Didgit(db.Model):
    __tablename__ = 'Didgit'
    id = db.Column(db.Integer, primary_key=True)
    number_brut = db.Column(db.Double, nullable=False)
    valeur = db.Column(db.Integer, nullable=False)
    user_id = db.Column(db.Integer, db.ForeignKey('User.id'), nullable=False)

controllers/eleves.py
from flask import render_template, Blueprint, request

# Création d'un blueprint 'eleves' pour regrouper les routes liées aux élèves
eleves = Blueprint("eleves", __name__)


# Liste simulée d'élèves pour l'exemple
liste_eleves = [
    {'nom': 'Dupont', 'prenom': 'Jean', 'classe': '2A'},
    {'nom': 'Dupont', 'prenom': 'Jeanne', 'classe': 'TG2'},
    {'nom': 'Marchand', 'prenom': 'Marie', 'classe': '2A'},
    {'nom': 'Martin', 'prenom': 'Adeline', 'classe': '1G1'},
    {'nom': 'Dupont', 'prenom': 'Lucas', 'classe': '2A'}
]


# Définition de la route '/eleves' accessible par HTTP GET
# Cas d'utilisation : http://127.0.0.1:5000/eleves?c=2A pour filtrer par classe
@eleves.route("/eleves")
def get_eleves():
    classe = request.args.get('c') # Recuperation de l'argument mis en parametre dans url ?c=...

    # Filtrage des élèves appartenant à la classe spécifiée si 'classe' est fourni
    if classe:
        eleves_selectionnes = [eleve for eleve in liste_eleves if eleve['classe'] == classe]

    else:  # Si aucun paramètre 'c' n'est fourni, la liste des élèves sélectionnés est vide
        eleves_selectionnes = []

    # Rendu du template 'eleves.html' en passant la liste filtrée des élèves
    return render_template("eleves.html", eleves=eleves_selectionnes)

controllers/heure.py
from datetime import datetime

from flask import render_template, Blueprint

h_m_s = Blueprint("heure", __name__)


@h_m_s.route('/heure')
def heure():
    date_local = datetime.now()
    h = date_local.hour
    m = date_local.minute
    s = date_local.second
    return render_template("heure.html", heure=h, minute=m, seconde=s)

controllers/pdfDownload.py
import tempfile

from flask import request, jsonify, Blueprint, render_template, session, redirect, url_for
import fitz  # PyMuPDF
import os

from extensions import db
from models.pdf_upload import PdfUpload

# Déclaration d'un nouveau blueprint pour les téléchargements de PDF
pdf_download = Blueprint('pdf_download', __name__)


@pdf_download.route('/upload_pdf', methods=['GET', 'POST'])
def upload_pdf() -> jsonify:
    if session.get("user_id") is None:
        return redirect(url_for('auth_bp.login'))
    if request.method == 'POST':  # Vérification de la présence du fichier dans la requête
        print(session["user_id"])
        if 'pdf' not in request.files:  # verification de recuperation de fichier non vide
            return render_template("UploadPdf.html", message="Pas de fichier selectionner")

        file = request.files["pdf"]

        if file.filename == '':  # Vérification que le fichier a un nom
            return render_template("UploadPdf.html", message="Fichier sans nom !!")

        if file and file.filename.endswith('.pdf'):  # Vérification de l'extension du fichier

            filepath = os.path.join(tempfile.gettempdir(), file.filename)
            file.save(filepath)

            # Extraction du texte du PDF
            text = extract_text_from_pdf(filepath)
            # Comptage des mots dans le texte extrait
            word_count = count_word(text)

            session['words_pdf'] = word_count

            # Création d'une nouvelle instance PdfUpload pour enregistrement en base de données
            new_pdf = PdfUpload(filename=file.filename,
                                word_count=word_count,
                                user_id=session['user_id']
                                )

            db.session.add(new_pdf)  # Ajout de l'instance à la session de la base de données
            db.session.commit()  # Enregistrement des modifications
            os.remove(filepath)  # suppresion du pdf

            return render_template("UploadPdf.html", message="Ok")
        else:
            return render_template("UploadPdf.html", message="Fichier du movais type")
    else:
        return render_template("UploadPdf.html")


def extract_text_from_pdf(filepath: str) -> str:
    # Fonction pour extraire le texte d'un fichier PDF
    text = ""
    with fitz.open(filepath) as pdf_text:  # Ouverture du fichier PDF avec PyMuPDF
        for page in pdf_text:  # Parcours des pages du PDF
            text += page.get_text()  # Extraction et ajout du texte de chaque page
    return text


def count_word(text: str) -> int:
    # Fonction pour compter le nombre de mots dans un texte
    words = text.split(" ")  # Séparation du texte en mots
    return len(words)  # Retour du nombre de mots

controllers/signup_login.py
from flask import Blueprint, request, jsonify, session, render_template, redirect, url_for
from werkzeug.security import check_password_hash

from extensions import db
from models.user import User

auth_bp = Blueprint('auth_bp', __name__)


@auth_bp.route('/singup', methods=['GET', 'POST'])
def singup():

    if request.method == 'POST':
        data = request.form
        print(data)
        new_username = data.get('username')
        new_password = data.get('password')
        print("new_password"+new_password)

        if User.query.filter_by(username=new_username).first():
            return render_template("index.html", message="Ce nom d'utilisateur est déjà pris")

        new_user = User(username=new_username)
        new_user.set_password(new_password)

        session['user_id'] = new_user.get_id()

        db.session.add(new_user)
        db.session.commit()

        return render_template("index.html")
    return render_template("singup.html")


@auth_bp.route('/login', methods=['GET', 'POST'])
def login():

    if request.method == 'POST':
        data = request.form
        print(data)

        username = data.get('username')
        password = data.get('password')

        # Vérifier si l'utilisateur existe
        user = User.query.filter_by(username=username).first()
        if not user or not check_password_hash(user.password, password):
            return render_template("login.html", message="Identifiants incorrect")

        # Si la vérification est réussie, stocker l'id de l'utilisateur dans la session
        session['user_id'] = user.get_id()
        return render_template("index.html")
    return render_template("login.html")


@auth_bp.route('/logout')
def logout():
    print(session)
    session.pop('user_id', None)
    return redirect(url_for("auth_bp.login"))

controllers/somme_des_chiffres.py
from flask import request, Blueprint, session, render_template, url_for, redirect
from extensions import db
from models.didgit import Didgit

# Création d'un blueprint 'somme_des_chiffres'
sum_way = Blueprint('somme_des_chiffres', __name__)


# Fonction pour calculer la somme des chiffres d'un nombre
def sum_didgit(number: int) -> int:
    return sum(int(digit) for digit in str(number))


# Outil de conversion de la response serveur en XML
# Version renvoie d'xml
def dict_to_xml(tag, d):
    parts = [f'<{tag}>']  # Début du tag XML
    for key, val in d.items():  # Pour chaque paire clé/valeur dans le dictionnaire
        parts.append(f'<{key}>{val}</{key}>')  # Ajout de la paire sous forme de balises XML
    parts.append(f'</{tag}>')  # Fermeture du tag XML
    return ''.join(parts)  # Assemblage et retour de la chaîne XML


# Définition de la route '/sum_didgit' accessible en GET
# Cas d'utilisation : http://localhost:5000/sum_didgit?number=123
@sum_way.route('/sum_didgit')
def request_sum_of_didgit():
    number = request.args.get('number', default=0, type=int)

    if session.get("user_id") is None:
        return redirect(url_for('auth_bp.login'))  # Assurez-vous d'importer `redirect`
    else:
        print(session["user_id"])
        resultat = sum_didgit(number) if number > 0 else 0

        if number > 0:
            new_number = Didgit(number_brut=number,
                                valeur=resultat,
                                user_id=session['user_id'])
            db.session.add(new_number)
            db.session.commit()

        return render_template("didgit.html", number=number, resultat=resultat)

controllers/statistique.py
from flask import Blueprint, render_template, request

from extensions import db
from sqlalchemy.sql import func
import plotly.graph_objs as go
import plotly.offline as pyo

from models.game_score import Score_Game
from models.pdf_upload import PdfUpload

stat = Blueprint("statistiques", __name__)


@stat.route('/top-users', methods=["GET","POST"])
def top_users_view():
    top_users = get_top_users_by_requests()
    pdfupload = get_uploads_by_user()

    data_type = request.form.get('data_type', 'game_sessions')

    if data_type == "game_sessions":
        fig = create_top_users_graph(top_users)
    else:
        fig = create_top_upload_graph(pdfupload)

    graph_html = pyo.plot(fig, include_plotlyjs=True, output_type='div')
    return render_template('statistique.html', graph_html=graph_html)


def get_top_users_by_requests():
    result = db.session.query(
        Score_Game.user_id, func.count(Score_Game.id).label('totals_games')  # reference de la colones données
    ).group_by(
        Score_Game.user_id
    ).order_by(
        func.count(Score_Game.id).desc()
    ).limit(5).all()

    return result


def get_uploads_by_user():
    result = db.session.query(
        PdfUpload.user_id, func.count(PdfUpload.id).label('totals_uploads')  # reference de la colones données
    ).group_by(
        PdfUpload.user_id
    ).order_by(
        func.count(PdfUpload.id).desc()
    ).limit(5).all()
    return result


def create_top_users_graph(top_users):
    user_ids = [str(user.user_id) for user in top_users]
    requests_counts = [user.totals_games for user in top_users]

    data = [go.Bar(x=user_ids, y=requests_counts)]
    layout = go.Layout(title='Top 5 utilisateurs par nombre de demandes')

    fig = go.Figure(data=data, layout=layout)
    return fig


def create_top_upload_graph(upload_by_user):
    user_ids = [str(user.user_id) for user in upload_by_user]
    requests_counts = [user.totals_uploads for user in upload_by_user]  # Attention les labels utilisaient dans les
    data = [go.Bar(x=user_ids, y=requests_counts)]                      # requestes importe beaucoup

    layout = go.Layout(title='visualisation des uploads de pdf du top 5 utilisateurs ')
    fig = go.Figure(data=data, layout=layout)
    return fig

controllers/the_Good_number.py
from random import randint

from flask import request, session, render_template, Blueprint, url_for, redirect

from extensions import db
from models.game_score import Score_Game

# Création d'un blueprint 'the_good_page' pour le jeu
game = Blueprint("the_good_page", __name__)


# Route '/jeu' accessible en GET pour commencer le jeu et en POST pour soumettre une réponse
@game.route('/jeu', methods=["GET", "POST"])
def jeu():

    if session.get("user_id") is None:
        return redirect(url_for('auth_bp.login'))
    # Traitement des soumissions de l'utilisateur
    if request.method == "POST":

        # Récupération du nombre proposé par l'utilisateur
        reponse = int(request.form.get('nombre'))
        # Enregistrement de la tentative dans la session
        session['essais'].append(reponse)

        # Vérification de la réponse de l'utilisateur par rapport au nombre mystère
        if reponse == session['nb']:
            session['en_cours'] = False
            message = "Bravo, c'est gagné !"
            #  Ajout des résultats en Bdd
            add_Score()

        elif reponse < session['nb']:
            message = "Non, c'est plus !"
        else:
            message = "Non, c'est moins !"

        # Décrémentation du nombre d'essais restants
        session['nb_essais'] = session['nb_essais'] - 1

        # Vérification si le joueur a épuisé tous ses essais
        if session['nb_essais'] == 0:
            session['en_cours'] = False
            message = "C'est perdu !"
            #  Ajout des résultats en Bdd
            add_Score()

        print(session)

        # Retour du template du jeu avec un message (résultat de la tentative)
        return render_template('game.html', message=message)

    else:  # Initialisation du jeu pour une requête GET
        nb_mystere = randint(0, 100)  # Génération d'un nombre aléatoire entre 0 et 100
        # Initialisation des variables de session pour le jeu
        session['nb'] = nb_mystere
        session['en_cours'] = True
        session['nb_essais'] = 10
        session['essais'] = []
        print(session)

        # Affichage du formulaire de jeu au début
        return render_template('game.html')


def add_Score():

    if 10 - session['nb_essais'] == 0:
        status = "Loose"
    else:
        status = "Win"

    score = Score_Game(
        user_id=session['user_id'],
        nb_essais=10 - session['nb_essais'],
        etat=status
    )
    db.session.add(score)
    db.session.commit()

templates/UploadPdf.html
{% extends "base.html" %}

{% block content %}
    <head>
        <title>Téléchargement PDF et Comptage de Mots</title>
    </head>
    <body>
        <h2>Téléchargement de fichier PDF</h2>
        <form action="/upload_pdf" method="post" enctype="multipart/form-data">
            <div class="col-md-6 mb-3 centre_auto">
                <label class="sr-only" for="pdf" >Choisir un fichier Pdf :</label>
                <input type="file"  class="form-control " name="pdf" id="pdf" accept=".pdf">
            </div>

            <hr class="mb-4">
            </div>
            <div class="col-md-6 mb-3 centre_auto">
                <input class="btn btn-primary btn-lg btn-block" type="submit" value="Uploader et Compter les Mots">
            </div>
        </form>
        {% if message == "Ok" %}
            <p>Voici le nombre de mots dans ton pdf : {{ session['words_pdf'] }}</p>
        {% else %}
            <p> {{ message }}</p>
        {% endif %}

    </body>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Mon appli</title>
    <link rel="canonical" href="https://getbootstrap.com/docs/4.0/examples/dashboard/">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">

</head>

<body>

    <nav id="navbar" class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0">
        <img src="{{ url_for('static', filename='img/img.png') }}" alt="logo" width="100" height="50">
      <ul class="navbar-nav px-3">
        <li class="nav-item text-nowrap">
             <a class="nav-link"
             {% if session['user_id'] %}
                href="{{ url_for('auth_bp.logout') }}">Sign out
             {% else %}
                href="{{ url_for('auth_bp.login') }}">Connect
             {% endif %}
             </a>
        </li>
      </ul>
    </nav>

    <div class="container-fluid">
      <div class="row">
        <nav class="col-md-2 d-none d-md-block bg-light sidebar">
          <div class="sidebar-sticky">
            <ul class="nav flex-column">
              <li data-path="/" class="nav-item">

                <a class="nav-link" href="{{ url_for('index') }}">
                  <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-home">
                      <path d="M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"></path>
                      <polyline points="9 22 9 12 15 12 15 22"></polyline>
                  </svg>
                   <span class="sr-only">(curent)</span>
                    Accueil
                </a>
              </li>

              <li data-path="/sum_didgit" class="nav-item">
                <a class="nav-link" href="{{ url_for('somme_des_chiffres.request_sum_of_didgit') }}">
                  <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-file">
                      <path d="M13 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V9z"></path>
                      <polyline points="13 2 13 9 20 9"></polyline>
                  </svg>
                  Sommes des chiffres
                </a>
              </li>

              <li data-path="/jeu" class="nav-item">
                <a class="nav-link" href="{{ url_for('the_good_page.jeu') }}">
                  <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-bar-chart-2">
                      <line x1="18" y1="2 0" x2="18" y2="10"></line>
                      <line x1="12" y1="20" x2="12" y2="4"></line>
                      <line x1="6" y1="20" x2="6" y2="14"></line>
                  </svg>
                  Nombre mystère
                </a>
              </li>

              <li data-path="/upload_pdf" class="nav-item">
                <a class="nav-link" href="{{ url_for('pdf_download.upload_pdf') }}">
                  <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-file-text"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"></path><polyline points="14 2 14 8 20 8"></polyline><line x1="16" y1="13" x2="8" y2="13"></line><line x1="16" y1="17" x2="8" y2="17"></line><polyline points="10 9 9 9 8 9"></polyline></svg>
                  Word in my pdf
                </a>
              </li>

              <li data-path="/top-users" class="nav-item">
                <a class="nav-link" href="{{ url_for('statistiques.top_users_view') }}">
                  <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-bar-chart-2"><line x1="18" y1="20" x2="18" y2="10"></line><line x1="12" y1="20" x2="12" y2="4"></line><line x1="6" y1="20" x2="6" y2="14"></line></svg>
                  Statistiques
                </a>
              </li>
            </ul>

            <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
              <span>Autres</span>
              <a class="d-flex align-items-center text-muted" href="#">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-plus-circle"><circle cx="12" cy="12" r="10"></circle><line x1="12" y1="8" x2="12" y2="16"></line><line x1="8" y1="12" x2="16" y2="12"></line></svg>
              </a>
            </h6>
              <li class="nav-item" >
                <a class="nav-link" href="#">
                  <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-file-text"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"></path><polyline points="14 2 14 8 20 8"></polyline><line x1="16" y1="13" x2="8" y2="13"></line><line x1="16" y1="17" x2="8" y2="17"></line><polyline points="10 9 9 9 8 9"></polyline></svg>
                  Futur_test
                </a>
              </li>
            </ul>
          </div>
        </nav>

        <main role="main" class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4"><div class="chartjs-size-monitor" style="position: absolute; inset: 0px; overflow: hidden; pointer-events: none; visibility: hidden; z-index: -1;"><div class="chartjs-size-monitor-expand" style="position:absolute;left:0;top:0;right:0;bottom:0;overflow:hidden;pointer-events:none;visibility:hidden;z-index:-1;"><div style="position:absolute;width:1000000px;height:1000000px;left:0;top:0"></div></div><div class="chartjs-size-monitor-shrink" style="position:absolute;left:0;top:0;right:0;bottom:0;overflow:hidden;pointer-events:none;visibility:hidden;z-index:-1;"><div style="position:absolute;width:200%;height:200%;left:0; top:0"></div></div></div>
            <div class=" justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">
                <div id="container">
                    {% block content %}{% endblock %}
                </div>
            </div>
        </main>

      </div>
    </div>

    <script src="{{ url_for('static', filename='js/app.js') }}"></script>
    <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.7.1/dist/Chart.min.js"></script>
</body>
</html>

templates/didgit.html
{% extends "base.html" %}

{% block content %}
    <h1 class="h2">Dans l'url ajouter "?number=123"</h1>

        {% if number > 0 %}
            <p>Voici le nombre donné : {{ number }}</p>
            <p>Resultat : {{ resultat }}</p>
            <p>À toi de trouver ce qu'on a fait avec ton nombre =).</p>
        {% else %}
            <p>Aucun nombre valide donné.</p>
        {% endif %}
{% endblock %}

templates/eleves.html
<DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Mon appli</title>
</head>
<body>
    <h1>Liste d'élèves</h1>
    {% if eleves|length == 0 %}
        <p>Aucun élève ne correspond à la recherche.</p>
    {% else %}
        <ul>
            {% for eleve in eleves %}
                <li>{{ eleve['nom'] }} {{ eleve['prenom'] }}, {{ eleve['classe'] }}</li>
            {% endfor %}
        </ul>
    {% endif %}
</body>
</html>

templates/game.html
{% extends "base.html" %}

{% block css %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/jeu.css') }}">
{% endblock %}

{% block content %}
<div id="jeu">
    <h1>Jeu du nombre mystère</h1>
    {% if session['en_cours'] %}
        <p>J'ai choisi un entier entre 0 et 100.</p>
        <form action="{{ url_for('the_good_page.jeu') }}" method="POST">
            <p>
                <label for="nombre">Devine le nombre :</label>
                <input type="number" name="nombre" id="nombre" required autofocus>
            </p>
            <p>
                <input class="btn" type="submit" value="Valider">
            </p>
        </form>
        <hr>
        {% if message %}
            {{ message }}
        {% endif %}
        <p>Il reste {{ session['nb_essais'] }} tentative(s) !</p>
        <a href="{{ url_for('the_good_page.jeu') }}">Recommencer</a>
        {% if session['essais'] != [] %}
            <table>
                <thead>
                    <tr>
                        <td>Tentative</td>
                        <td>Résultat</td>
                    </tr>
                </thead>
                <tbody>
                {% for essai in session['essais'] %}
                    <tr>
                        <td>{{ essai }}</td>
                        <td>{{ "C'est plus !" if session['nb'] > essai else "C'est moins !" }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        {% endif %}
    {% else %}
        <hr>
        {% if message %}
            {{ message }}
            {% if session['nb_essais'] > 0 %}
                <p>Le nombre mystère était bien {{ session['nb'] }} !</p>
                <p>Tu as trouvé en {{ 10-session['nb_essais'] }} tentative(s).</p>
            {% else %}
                <p>Le nombre mystère était {{ session['nb'] }}...</p>
            {% endif %}
        {% endif %}
        <a href="{{ url_for('the_good_page.jeu') }}">Rejouer</a>
    {% endif %}
</div>
{% endblock %}

templates/heure.html
{% extends "base.html" %}
{% block content %}
    <h1> Quelle heure est-il ?</h1>
    <p> Il est {{ heure }}:{{ minute }}:{{ seconde }}</p>
{% endblock %}

templates/index.html
{% extends "base.html" %}
{% block content %}
<p>Hello World! Index!!</p>
{% endblock %}

templates/login.html
{% extends "base.html" %}

{% block content %}
<h1>Page de connexion</h1>
<form class="form-signin" action="/auth/login" method="POST">

    <div>
            <div class="col-md-6 mb-3 centre_auto">
                <label class="sr-only" for="username">Username : </label>
                <input type="text" class="form-control" id="username" name="username" placeholder="Username" value="" required>
                <div class="invalid-feedback">
                  Valid first name is required.
                </div>
            </div>
            <div class="col-md-6 mb-3 centre_auto">
                <label class="sr-only" for="password">Password : </label>
                <input type="password" class="form-control" id="password" name="password" placeholder="Password" value="" required>
                <div class="invalid-feedback">
                  Valid first name is required.
                </div>
                <hr class="mb-4">
            </div>
            <div class="col-md-6 mb-3 centre_auto">
                <input class="btn btn-primary btn-lg btn-block" type="submit" value="Se connecter">
            </div>

    {% if message %}
        <p style="color: red">{{ message }}</p>
    {% endif %}
    </div>
</form>


    <a href="{{ url_for('auth_bp.singup') }}"> S'inscrire </a>

{% endblock %}

templates/signup.html
<!DOCTYPE html>
<html>
<head>
    <title>Inscription</title>
</head>
<body>
    <h2>Inscription</h2>
    <form action="/auth/signup" method="post">
        <label for="username">Nom d'utilisateur :</label>
        <input type="text" id="username" name="username" required>
        <label for="password">Mot de passe:</label>
        <input type="password" id="password" name="password" required>
        <input type="submit" value="S'inscrire">
    </form>
</body>
</html>

templates/singup.html
{% extends "base.html" %}
{% block content %}
    <h1 class="h2">Inscription</h1>
    <form class="form-signin text-center" action="/auth/singup" method="post">
        <div >
            <div class="col-md-6 mb-3 centre_auto">
                <label class="sr-only" for="username">Nom d'utilisateur :</label>
                <input type="text" class="form-control" id="username" name="username" placeholder="Username" required>
                <div class="invalid-feedback">
                  Valid first name is required.
                </div>
            </div>
            <div class="col-md-6 mb-3 centre_auto">
                <label class="sr-only" for="password">Mot de passe:</label>
                <input class="form-control" type="password" id="password" name="password" placeholder="Password" required="">
                <div class="invalid-feedback">
                  Valid last name is required.
                </div>
            </div>
            <hr class="mb-4">
            <div class="col-md-6 mb-3 centre_auto">
                <input class="btn btn-primary btn-lg btn-block" type="submit" value="S'inscrire">
            </div>
        </div>
    </form>
     {% if message %}
        <p style="color: red">{{ message }}</p>
     {% endif %}
{% endblock %}

templates/statistique.html
{% extends "base.html" %}

{% block content %}

    <h1 class="h2">Dashboard</h1>
    <div class="btn-toolbar mb-2 mb-md-0">
        <div class="btn-group mr-2">
            <form method="POST">
                <select name="data_type">
                    <option value="game_sessions">Sessions de Jeu</option>
                    <option value="help_requests">Requetes d'Aide</option>
                </select>
                <input class="btn btn-sm btn-outline-primary" type="submit" value="Visualiser">
            </form>
        </div>
    </div>
    <div class="my-4 chartjs-render-monitor" id="myChart" style="display: block">
        {{ graph_html|safe }}
    </div>


{% endblock %}